version: "3.9"
services:
  nginx:
    container_name: pgp2_nginx_${CONFIG_ENV}_${NODE_ENV}
    image: jonasal/nginx-certbot:latest
    # image: pgp2_nginx_${CONFIG_ENV}_${NODE_ENV}
    # build: ./
    env_file: .env
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d/${CONFIG_ENV}_${NODE_ENV}.conf:/etc/nginx/user_conf.d/vhosts.conf
      - ./user_conf.d/proxy.conf:/etc/nginx/user_conf.d/proxy.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html

volumes:
  nginx_secrets:

networks:
  default:
    external:
      name: pgp
