-- DATABASE
GRANT ALL ON DATABASE pgp2 TO pgp2;

GRANT ALL ON DATABASE pgp2 TO "ADMIN";

GRANT ALL ON DATABASE pgp2 TO "USER";

-- TABLES
ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO "ADMIN";

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO pgp2;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO "USER";

-- SEQUENCES
ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO "ADMIN";

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO "USER";

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO pgp2;

-- SCHEMA
GRANT ALL ON SCHEMA public TO "ADMIN";

GRANT ALL ON SCHEMA public TO "USER";

GRANT ALL ON SCHEMA public TO pgp2;